In [6]:
import pandas as pd

maf = pd.read_csv(
    '/Users/naigelu/Desktop/Imperial College London/Year 2/STJU Summer Internship/Project 130/Lung Cancer/cohortMAF.2026-07-20.maf.gz',
    sep="\t",
    comment="#"
)

maf.head()

print(maf.columns)

Index(['Hugo_Symbol', 'Entrez_Gene_Id', 'Center', 'NCBI_Build', 'Chromosome',
       'Start_Position', 'End_Position', 'Strand', 'Variant_Classification',
       'Variant_Type',
       ...
       'GDC_FILTER', 'COSMIC', 'hotspot', 'tumor_bam_uuid', 'normal_bam_uuid',
       'RNA_Support', 'RNA_depth', 'RNA_ref_count', 'RNA_alt_count',
       'callers'],
      dtype='object', length=140)

In [8]:
print("Rows:", maf.shape[0])
print("Columns:", maf.shape[1])
    #tells you the dimensions, the number of rows and columns

maf.head()

Rows: 194729
Columns: 140

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,...,GDC_FILTER,COSMIC,hotspot,tumor_bam_uuid,normal_bam_uuid,RNA_Support,RNA_depth,RNA_ref_count,RNA_alt_count,callers
0,MTOR,2475,BI,GRCh38,chr1,11114828,11114828,+,Missense_Mutation,SNP,...,NaN,NaN,N,5f3f8246-619c-4a95-b6fc-51ad2c54083e,55c85543-b90f-4254-9ec8-0e5368f7e74a,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2
1,DISP3,57540,BI,GRCh38,chr1,11535561,11535561,+,Missense_Mutation,SNP,...,NaN,NaN,N,5f3f8246-619c-4a95-b6fc-51ad2c54083e,55c85543-b90f-4254-9ec8-0e5368f7e74a,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2
2,VPS13D,55187,BI,GRCh38,chr1,12277107,12277107,+,Silent,SNP,...,NaN,NaN,N,5f3f8246-619c-4a95-b6fc-51ad2c54083e,55c85543-b90f-4254-9ec8-0e5368f7e74a,Unknown,NaN,NaN,NaN,muse;mutect2
3,HSPG2,3339,BI,GRCh38,chr1,21852793,21852793,+,Missense_Mutation,SNP,...,NaN,NaN,N,5f3f8246-619c-4a95-b6fc-51ad2c54083e,55c85543-b90f-4254-9ec8-0e5368f7e74a,Unknown,NaN,NaN,NaN,muse;mutect2
4,E2F2,1870,BI,GRCh38,chr1,23509980,23509980,+,Missense_Mutation,SNP,...,NaN,NaN,N,5f3f8246-619c-4a95-b6fc-51ad2c54083e,55c85543-b90f-4254-9ec8-0e5368f7e74a,Unknown,NaN,NaN,NaN,muse;mutect2;varscan2

In [9]:
important_columns = [
    "Hugo_Symbol",
    "NCBI_Build",
    "Chromosome",
    "Start_Position",
    "End_Position",
    "Reference_Allele",
    "Tumor_Seq_Allele2",
    "Variant_Classification",
    "Variant_Type",
    "Tumor_Sample_Barcode",
    "HGVSc",
    "HGVSp_Short",
    "Transcript_ID",
    "GDC_FILTER"
]

maf[important_columns].head()


# The theory behind each selected column:
    #Hugo_Symbol: gene name, such as TP53
    #NCBI_Build: genome assembly
    #Chromosome: chromosome
    #Start_Position, End_Position: genomic coordinates
    #Reference_Allele: original DNA base
    #Tumor_Seq_Allele2: mutated DNA base
    #Variant_Classification: consequence, such as missense
    #Variant_Type: SNP, insertion, deletion
    #Tumor_Sample_Barcode: tumour sample ID
    #HGVSc: coding DNA mutation
    #HGVSp_Short: protein mutation
    #Transcript_ID: transcript affected
    #GDC_FILTER: quality-related annotation

,Hugo_Symbol,NCBI_Build,Chromosome,Start_Position,End_Position,Reference_Allele,Tumor_Seq_Allele2,Variant_Classification,Variant_Type,Tumor_Sample_Barcode,HGVSc,HGVSp_Short,Transcript_ID,GDC_FILTER
0,MTOR,GRCh38,chr1,11114828,11114828,C,A,Missense_Mutation,SNP,TCGA-86-A4D0-01A-11D-A24D-08,c.7149G>T,p.L2383F,ENST00000361445,NaN
1,DISP3,GRCh38,chr1,11535561,11535561,G,A,Missense_Mutation,SNP,TCGA-86-A4D0-01A-11D-A24D-08,c.3733G>A,p.V1245I,ENST00000294484,NaN
2,VPS13D,GRCh38,chr1,12277107,12277107,G,A,Silent,SNP,TCGA-86-A4D0-01A-11D-A24D-08,c.3519G>A,p.L1173=,ENST00000620676,NaN
3,HSPG2,GRCh38,chr1,21852793,21852793,C,G,Missense_Mutation,SNP,TCGA-86-A4D0-01A-11D-A24D-08,c.6631G>C,p.A2211P,ENST00000374695,NaN
4,E2F2,GRCh38,chr1,23509980,23509980,G,A,Missense_Mutation,SNP,TCGA-86-A4D0-01A-11D-A24D-08,c.1214C>T,p.P405L,ENST00000361729,NaN

In [13]:
maf["NCBI_Build"].value_counts(dropna=False)
    #Checking they all have the same genome build

NCBI_Build
GRCh38    194729
Name: count, dtype: int64

In [14]:
print("Genome assemblies:", maf["NCBI_Build"].unique())

Genome assemblies: ['GRCh38']

In [15]:
maf["Variant_Classification"].value_counts()
    # describes the biological consequence of each mutation
    #Missense_Mutation: changes one amino acid
    #Silent: DNA changes, but amino acid stays the same
    #Nonsense_Mutation: creates a premature stop codon
    #Frame_Shift_Del: deletion shifts the reading frame
    #Splice_Site: may affect RNA splicing
    #Intron: located in a non-coding intron

Variant_Classification
Missense_Mutation         126254
Silent                     42349
Nonsense_Mutation          10454
Frame_Shift_Del             4256
Splice_Site                 3719
Intron                      1730
RNA                         1459
Frame_Shift_Ins             1290
Splice_Region               1110
In_Frame_Del                 406
3'UTR                        395
5'Flank                      328
5'UTR                        272
3'Flank                      270
Translation_Start_Site       211
Nonstop_Mutation             175
In_Frame_Ins                  49
IGR                            2
Name: count, dtype: int64

In [16]:
maf["Variant_Type"].value_counts(dropna=False)
#SNP = one base changed
#DEL = deletion
#INS = insertion

Variant_Type
SNP    188298
DEL      4998
INS      1423
ONP         6
TNP         4
Name: count, dtype: int64

In [23]:
maf["GDC_FILTER"].value_counts(dropna=False)

GDC_FILTER
NaN          191643
NonExonic      3075
gdc_pon          11
Name: count, dtype: int64

In [22]:
maf[["GDC_FILTER"]].drop_duplicates().head(20)

      GDC_FILTER
0            NaN
37     NonExonic
42400    gdc_pon

In [24]:
print("Unique full sample barcodes:")
print(maf["Tumor_Sample_Barcode"].nunique())

maf["Tumor_Sample_Barcode"].head(10)

Unique full sample barcodes:
616

0    TCGA-86-A4D0-01A-11D-A24D-08
1    TCGA-86-A4D0-01A-11D-A24D-08
2    TCGA-86-A4D0-01A-11D-A24D-08
3    TCGA-86-A4D0-01A-11D-A24D-08
4    TCGA-86-A4D0-01A-11D-A24D-08
5    TCGA-86-A4D0-01A-11D-A24D-08
6    TCGA-86-A4D0-01A-11D-A24D-08
7    TCGA-86-A4D0-01A-11D-A24D-08
8    TCGA-86-A4D0-01A-11D-A24D-08
9    TCGA-86-A4D0-01A-11D-A24D-08
Name: Tumor_Sample_Barcode, dtype: object

In [27]:
maf["Sample_ID"] = maf["Tumor_Sample_Barcode"].str[:16]

In [28]:
print("Unique shortened sample IDs:")
print(maf["Sample_ID"].nunique())

Unique shortened sample IDs:
575

In [29]:
# PASS is encoded as an empty GDC_FILTER in this MAF; the literal
# string "PASS" never appears (see the value_counts cell above).
filtered_maf = maf[
    (maf["Variant_Classification"] == "Missense_Mutation") &
    (maf["Variant_Type"] == "SNP") &
    (maf["GDC_FILTER"].isna() | (maf["GDC_FILTER"] == ""))
].copy()

In [30]:
print(maf.shape)
print(maf["NCBI_Build"].value_counts(dropna=False))
print(maf["Variant_Classification"].value_counts().head(15))
print(maf["Variant_Type"].value_counts(dropna=False))
print(maf["GDC_FILTER"].value_counts(dropna=False).head(20))

(194729, 141)
NCBI_Build
GRCh38    194729
Name: count, dtype: int64
Variant_Classification
Missense_Mutation         126254
Silent                     42349
Nonsense_Mutation          10454
Frame_Shift_Del             4256
Splice_Site                 3719
Intron                      1730
RNA                         1459
Frame_Shift_Ins             1290
Splice_Region               1110
In_Frame_Del                 406
3'UTR                        395
5'Flank                      328
5'UTR                        272
3'Flank                      270
Translation_Start_Site       211
Name: count, dtype: int64
Variant_Type
SNP    188298
DEL      4998
INS      1423
ONP         6
TNP         4
Name: count, dtype: int64
GDC_FILTER
NaN          191643
NonExonic      3075
gdc_pon          11
Name: count, dtype: int64